# Generated by Django 3.0.5 on 2020-04-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, null=True)),
                ('star', models.DecimalField(decimal_places=1, default=1, max_digits=5, null=True)),
                ('latitude', models.IntegerField(null=True)),
                ('longitude', models.IntegerField(null=True)),
                ('photo', models.ImageField(blank=True, upload_to='img')),
                ('opened_date', models.DateField(blank=True, default=None, null=True)),
                ('entry', models.TimeField()),
                ('departure', models.TimeField()),
                ('owner', models.CharField(blank=True, default='', max_length=30, null=True)),
            ],
        ),
    ]
